# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import usermanagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('hash_code', models.CharField(default=usermanagement.models._generateHash, max_length=500, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('roles', models.CharField(choices=[('T', 'Tester'), ('D', 'Developer')], max_length=1, null=True)),
                ('hash_code', models.CharField(default=usermanagement.models._generateHash, max_length=500, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
