# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import usermanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='hash_code',
            field=models.CharField(default=usermanagement.models._generateHash, editable=False, max_length=500, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash_code',
            field=models.CharField(default=usermanagement.models._generateHash, editable=False, max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
