# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20170329_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('m', 'Manager'), ('u', 'User')], max_length=1, null=True),
        ),
    ]
