# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_remove_profile_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='u', editable=False, max_length=1),
        ),
    ]
